spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:~/stena-h2db/h2db;AUTO_SERVER=TRUE;MODE=POSTGRESQL;NON_KEYWORDS=KEY,VALUE
    #url: jdbc:h2:mem:stenadb;MODE=POSTGRESQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=FALSE;NON_KEYWORDS=KEY,VALUE
    username:
    password:
    driverClassName: org.h2.Driver
logging:
  config: classpath:log4j2-local.yaml