server:
  servlet:
    context-path: /stena
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: ${spring.profiles.active}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
logging:
  config: classpath:log4j2.yaml