name: Deploy to Google Cloud Run

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-north1
  SERVICE_NAME: my-cloud-run-service
  IMAGE_URL: gcr.io/${{ secrets.GCP_PROJECT_ID }}/stenaapp:latest
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_URL }} .
          docker push ${{ env.IMAGE_URL }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: .tf/app
        #        run: terraform init -backend-config="bucket=${PROJECT_ID}-terraform-state" -backend-config="prefix=terraform/state"
        run: terraform init

      - name: Terraform Apply
        working-directory: .tf/app
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var="service_name=${{ env.SERVICE_NAME }}" \
            -var="image_url=${{ env.IMAGE_URL }}" \
            -var="db_user=${{ env.DB_USER }}" \
            -var="db_password=${{ env.DB_PASSWORD }}"